In [15]:
import pandas as pd

df = pd.read_csv('vvv.csv')
df.head(25)

    1  2  3  4  5  6  7
0   1  1  1  1  1  1  1
1   1  0  1  1  1  1  1
2   1  1  1  1  1  1  1
3   1  0  1  1  0  1  1
4   0  1  0  1  0  1  1
5   0  0  0  0  1  1  1
6   1  1  1  0  1  1  1
7   1  0  0  1  1  1  1
8   0  1  0  0  1  1  1
9   1  0  1  1  1  1  0
10  0  1  1  1  1  1  0
11  1  1  1  1  0  1  1
12  1  0  1  0  1  1  0
13  0  1  0  0  0  1  0
14  0  1  0  0  1  0  1
15  0  0  1  0  1  0  1
16  0  1  1  0  1  0  1
17  0  0  1  0  1  0  0
18  0  1  1  1  0  0  0
19  0  1  1  1  0  0  0
20  0  1  0  1  1  0  0
21  0  1  0  1  0  0  0
22  0  0  0  1  0  0  0
23  0  0  0  0  1  0  0
24  0  0  0  0  0  0  0

In [16]:
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [17]:
print ("Dataset Lenght:: ", len(df))
print ("Dataset Shape:: ", df.shape)

Dataset Lenght::  25
Dataset Shape::  (25, 7)

In [18]:
X = df.values[:, 1:7]
Y = df.values[:,0]

In [20]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.2, random_state = 100)

In [27]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100)
clf_entropy.fit(X_train, y_train)
tree.export_graphviz(clf_entropy, out_file='ttt.dot')